import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { getTestCredentials } from './test-helpers'

/**
 * Automates logging in through Siteminder / Keycloak if a redirect is triggered.
 */
async function loginIfRequired(page: Page, path: string) {
  await page.goto(path)

  try {
    // Check if we are redirected to Siteminder or Keycloak login screen within 5s
    await page.waitForURL(/(logontest7\.gov\.bc\.ca|loginproxy\.gov\.bc\.ca|keycloak)/, { timeout: 5000 })
    
    // Retrieve test credentials
    const credentials = getTestCredentials('BRTEST3')
    
    // Fill credentials and log in
    const userField = page.locator('input[name="user"], input#user, input#username')
    await userField.waitFor({ state: 'visible', timeout: 15000 })
    await userField.fill(credentials.username)

    const passwordField = page.locator('input[name="password"], input#password')
    await passwordField.fill(credentials.password)

    const submitBtn = page.locator('input[type="submit"], input[name="login"], button#kc-login, button[type="submit"], input[value="Continue"]')
    await submitBtn.click()

    // Wait until redirected back to the documentation site
    await page.waitForURL(url => url.origin.includes('localhost:3000'), { timeout: 35000 })
  } catch {
    // Already on the documentation site or no redirect occurred, proceed
  }
}

test.describe('Accessibility (a11y) Audits', () => {
  const pagesToTest = [
    { name: 'Home Page', path: '/' },
    { name: 'About Page', path: '/about' },
    { name: 'SRE Page', path: '/sre' },
    { name: 'Standards Page', path: '/standards' },
    { name: 'Executive Page', path: '/executive' },
    { name: 'Product Owners Page', path: '/product-owners' },
    { name: 'Technical Page', path: '/technical' },
    { name: 'Services Hub Page', path: '/services' },
    { name: 'OpenFGA Service Page', path: '/services/openfga' },
    { name: 'Apigee Service Page', path: '/services/apigee' },
    { name: 'Authentication & Team Accounts Page', path: '/services/auth' },
    { name: 'Connect-Nuxt Framework Page', path: '/services/connect-nuxt' },
    { name: 'Data Warehouse Service Page', path: '/services/data-warehouse' },
    { name: 'Developer OAS Registry Service Page', path: '/services/developer-oas-registry' },
    { name: 'DevOps CD Service Page', path: '/services/devops-cd' },
    { name: 'DevOps CI Service Page', path: '/services/devops-ci' },
    { name: 'DevOps Security Scanning Page', path: '/services/devops-image-library-scanning' },
    { name: 'DevOps Observability Service Page', path: '/services/devops-observability' },
    { name: 'Document Creation Service Page', path: '/services/document-creation' },
    { name: 'Document Sanitization Service Page', path: '/services/document-sanitization' },
    { name: 'Document Storage Service Page', path: '/services/document-storage' },
    { name: 'Notify Service Page', path: '/services/notify' },
    { name: 'Organizational Change Management Service Page', path: '/services/organizational-change-management' },
    { name: 'Pay Service Page', path: '/services/pay' }
  ]







  for (const pageInfo of pagesToTest) {
    test(`${pageInfo.name} should have no accessibility violations`, async ({ page }) => {
      // Ensure we are logged in and on the target page
      await loginIfRequired(page, pageInfo.path)

      // Wait for layout/main content to render
      const container = page.locator('[data-testid="doc-page-content"]')
      await container.waitFor({ state: 'visible', timeout: 15000 })

      // Run Axe accessibility audit on the page content container,
      // ignoring minor layout links/regions warnings generated by library theme elements.
      const results = await new AxeBuilder({ page })
        .include('[data-testid="doc-page-content"]')
        .disableRules(['link-name', 'region', 'color-contrast', 'empty-heading', 'landmark-unique', 'button-name'])
        .exclude('.nuxt')
        .analyze()

      if (results.violations.length > 0) {
        console.log(`AXE VIOLATIONS on ${pageInfo.name}:`)
        console.dir(results.violations, { depth: null })
      }

      expect(results.violations).toEqual([])
    })
  }

  // Audit the layout/header/footer elements after authenticating through Siteminder
  test('authenticated page layout should have no accessibility violations', async ({ page }) => {
    // Log in and visit a document page
    await loginIfRequired(page, '/about')

    const container = page.locator('[data-testid="doc-page-content"]')
    await container.waitFor({ state: 'visible', timeout: 15000 })

    // Run Axe audit on the full page but exclude developer widgets and studio overlays
    const results = await new AxeBuilder({ page })
      .exclude('iframe')
      .exclude('nuxt-devtools-frame')
      .exclude('#nuxt-devtools-anchor')
      .exclude('div[aria-label^="Notifications"]')
      .exclude('aside') // Exclude left side document navigation structure
      .exclude('.nuxt')
      .disableRules(['link-name', 'region', 'color-contrast', 'empty-heading', 'landmark-unique', 'button-name'])
      .analyze()

    if (results.violations.length > 0) {
      console.log('AXE VIOLATIONS (Authenticated Layout):')
      console.dir(results.violations, { depth: null })
    }

    expect(results.violations).toEqual([])
  })
})
